### ISSUE TITLE
Thunder Tree: Sprinkle Water (First Option)

### ISSUE THREAD

**Issue by ftlvz5** [KhryDL/Vroom-vroomMachine#10]
on f1303cc836d581d845a4563e269c4c7ee11b3ff5
The script chooses the first option (sprinkle water) now, and gets stuck here.
Not necessarily the wrong option, both options give the EGO gift, but first option need to repeatedly sprinkle water to solve the event.
The amount of times is random.
![thunder_tree_sprinkle_wrong_option](https://user-images.githubusercontent.com/128587928/227789273-3920dca4-03d2-4953-aa21-e1e087b0f5e2.png)
![image](https://user-images.githubusercontent.com/128587928/227789950-6dbf3386-93a7-43b4-b223-dce48db1eb1a.png)

The second option is more robust, it has a set amount of steps. It has no dice check (from my experience) like it says in the above image from the abno event sheet.
The screenshots are in the gdrive.

Video demo of second option. (Note there is no initial text in the box because I've restarted the game to get the options select back)
https://user-images.githubusercontent.com/128587928/227790477-25816137-8928-47b4-9f8e-9fd59d9a5cfa.mp4

**Comment by KhryDL** [comment]
The script can complete the sprinkle event, i just didn't update the "continue" button check when i fixed the continue button not being recognized elsewhere.

The only thing i'm missing are the actual buttons you have to press in order to advance the sprinkle option, from the screenshot it seems like you have to press sprinkle, then skip, then proceed end repeat until continue appears, the script can do it just fine, i just need confirmation that those are the steps needed to complete the cycle

**Comment by KhryDL** [comment]
i just got this abno and the script cleared it just fine, closing for now
